let paises = {
"Albania" : ["Albania"],
"Andorra" : ["Andorra"],
"Austria" : ["Austria"],
"Belgium" : ["Bélgica", "Belgica"],
"Belorussia" : ["Bielorrusia"],
"Bosnia-Herzegovina" : ["Bosnia-Herzegovina"],
"Bulgaria" : ["Bulgaria"],
"Croatia" : ["Croacia"],
"Cyprus" : ["Chipre"],
"Czech Republic" : ["Chequia"],
"Denmark" : ["Dinamarca"],
"Estonia" : ["Estonia"],
"Finland" : ["Finlandia"],
"France" : ["Francia"],
"Germany" : ["Alemania"],
"Greece" : ["Grecia"],
"Holy See" : ["Santa Sede"],
"Hungary" : ["Hungría", "Hungria"],
"Iceland" : ["Islandia"],
"Ireland" : ["Irlanda"],
"Italy" : ["Italia"],
"Kosovo" : ["Kosovo"],
"Latvia" : ["Letonia"],
"Liechtenstein" : ["Liechtenstein"],
"Lithuania" : ["Lituania"],
"Luxembourg" : ["Luxemburgo"],
"Macedonia" : ["Macedonia"],
"Malta" : ["Malta"],
"Moldova" : ["Moldau, Moldavien"],
"Monaco" : ["Mónaco"],
"Montenegro" : ["Montenegro"],
"Norway" : ["Noruega"],
"Poland" : ["Polonia"],
"Portugal" : ["Portugal"],
"Romania" : ["Rumanía", "Rumania"],
"Russia" : ["Rusia"],
"San Marino" : ["San Marino"],
"Serbia" : ["Serbia"],
"Slovakia" : ["Eslovaquia"],
"Slovenia" : ["Eslovenia"],
"Spain" : ["España"],
"Sweden" : ["Suecia"],
"Switzerland" : ["Suiza"],
"The Netherlands" : ["Países Bajos", "Paises Bajos", "Holanda"],
"The Ukraine" : ["Ucrania"],
"Turkey" : ["Turquía"],
"United Kingdom" : ["Reino Unido", "Inglaterra", "Gales", "Escocia", "Irlanda del norte", "Irlanda Norte"],
"Vatican City" : ["Vaticano"],
"Antigua and Barbuda" : ["Antigua y Barbuda"],
"Argentina" : ["Argentina"],
"Bahamas" : ["Bahamas"],
"Barbados" : ["Barbados"],
"Belize" : ["Belice"],
"Bolivia" : ["Bolivia"],
"Brazil" : ["Brasil"],
"Canada" : ["Canadá", "Canada"],
"Colombia" : ["Colombia"],
"Costa Rica" : ["Costa Rica"],
"Cuba" : ["Cuba"],
"Chile" : ["Chile"],
"Dominica" : ["Dominica"],
"Dominican Republic" : ["República Dominicana", "Republica Dominicana", "Dominica", "Dominicana"],
"Ecuador" : ["Ecuador"],
"El Salvador" : ["El Salvador"],
"Greenland" : ["Groenlandia"],
"Grenada" : ["Granada"],
"Guatemala" : ["Guatemala"],
"Guyana" : ["Guayana"],
"Haiti" : ["Haití", "Haiti"],
"Honduras" : ["Honduras"],
"Jamaica" : ["Jamaica"],
"Mexico" : ["México", "Mexico", "Mejico"],
"Nicaragua" : ["Nicaragua"],
"Panama" : ["Panamá", "Panama"],
"Paraguay" : ["Paraguay"],
"Peru" : ["Perú", "Peru"],
"Saint Vincent and the Grenadines" : ["San Vicente y las Granadinas", "San Vicente"],
"St. Kitts und Nevis" : ["San Cristóbal y Nieves", "San Cristobal y Nieves", "San Cristobal"],
"Suriname" : ["Surinam"],
"Trinidad and Tobago" : ["Trinidad y Tobago", "Trinidad"],
"Uruguay" : ["Uruguay"],
"United States of America" : ["Estados Unidos (EEUU)", "EEUU", "USA", "Estados Unidos"],
"Venezuela" : ["Venezuela"],
"Algeria" : ["Argelia"],
"Angola" : ["Angola"],
"Benin" : ["Benin"],
"Botswana" : ["Botswana"],
"Burkina Faso" : ["Burkina Faso"],
"Burundi" : ["Burundi"],
"Cameroon" : ["Camerún", "Camerun"],
"Cape Verde Islands" : ["Islas de Cabo Verde"],
"Central African Republic" : ["República Centroafricana", "Republica Centroafricana"],
"Comoros" : ["Comores"],
"Congo" : ["Congo"],
"Chad" : ["Chad"],
"Egypt" : ["Egipto"],
"Equatorial Guinea" : ["Guinea Ecuatorial"],
"Eritrea" : ["Eritrea"],
"Ethiopia" : ["Etiopía", "Etiopia"],
"Gabon" : ["Gabón"],
"Gambia" : ["Gambia"],
"Ghana" : ["Ghana"],
"Guinea" : ["Guinea"],
"Guinea-Bissau" : ["Guinea-Bissau", "Guinea Bissau"],
"Ivory Coast" : ["Costa de Marfil", "Marfil", "Costa Marfil"],
"Kenya" : ["Kenia"],
"Lesotho" : ["Lesoto"],
"Liberia" : ["Liberia"],
"Libya" : ["Libia"],
"Madagascar" : ["Madagascar"],
"Malawi" : ["Malaui"],
"Mali" : ["Mali"],
"Mauritania" : ["Mauritania"],
"Mauritius" : ["Mauricio"],
"Morocco" : ["Marruecos"],
"Mozambique" : ["Mozambique"],
"Namibia" : ["Namibia"],
"Niger" : ["Niger"],
"Nigeria" : ["Nigeria"],
"Rwanda" : ["Ruanda"],
"Senegal" : ["Senegal"],
"Seychelles" : ["Seychelles"],
"Sierra Leone" : ["Sierra Leona"],
"Somalia" : ["Somalia"],
"South Africa" : ["Sudáfrica", "Sudafrica"],
"Sudan" : ["Sudán", "Sudan"],
"Swaziland" : ["Suazilandia"],
"Tanzania" : ["Tanzania"],
"Togo" : ["Togo"],
"Tunisia" : ["Túnez", "Tunez"],
"Uganda" : ["Uganda"],
"Zambia" : ["Zambia"],
"Zimbabwe" : ["Zimbabue"],
"Laos" : ["Laos"],
"Lebanon" : ["Líbano", "Libano"],
"Afghanistan" : ["Afganistán", "Afganistan"],
"Armenia" : ["Armenia"],
"Azerbaijan" : ["Azerbaiyán"],
"Bahrain" : ["Bahréin"],
"Bangladesh" : ["Bangladesh"],
"Brunei" : ["Brunei"],
"Cambodia" : ["Camboya"],
"China" : ["China"],
"East Timor" : ["Timor oriental"],
"Georgia" : ["Georgia"],
"India" : ["India"],
"Indonesia" : ["Indonesia"],
"Iran" : ["Irán", "Iran"],
"Iraq" : ["Irak"],
"Israel" : ["Israel"],
"Japan" : ["Japón", "Japon"],
"Jordan" : ["Jordania"],
"Kazakhstan" : ["Kazajstán", "Kazajstan"],
"Kuwait" : ["Kuwait"],
"Kyrgyzstan" : ["Kirgisistán", "Kirgisistan"],
"Malaysia" : ["Malasia"],
"Maldives" : ["Maldivas"],
"Mongolia" : ["Mongolia"],
"Myanmar" : ["Birmania, Myanmar"],
"Nepal" : ["Nepal"],
"North Korea" : ["Corea del Norte"],
"Oman" : ["Omán", "Oman"],
"Pakistan" : ["Paquistán", "Paquistan"],
"Philippines" : ["Filipinas"],
"Qatar" : ["Qatar"],
"Saudia Arabia" : ["Arabia Saudí", "Arabia Saudi", "Arabia Saudita"],
"Singapore" : ["Singapur"],
"South Korea" : ["Corea del Sur"],
"Sri Lanka" : ["Sri Lanka"],
"Syria" : ["Siria"],
"Thailand" : ["Tailandia"],
"United Arab Emirates" : ["Emiratos Árabes Unidos", "Emiratos", "Emiratos Arabes", "Emiratos Arabes Unidos"],
"Uzbekistan" : ["Uzbekistán", "Uzbekistan"],
"Vietnam" : ["Vietnam"],
"Yemen" : ["Yemen"],
"Australia" : ["Australia"],
"Cook Islands" : ["Islas Cook"],
"Marshall Islands" : ["Islas Marshall"],
"Solomon Islands" : ["Islas Salomón", "Islas Salomon"],
"Kiribati" : ["Kiribati"],
"Micronesia" : ["Micronesia"],
"Nauru" : ["Nauru"],
"New Zealand" : ["Nueva Zelanda"],
"Niue" : ["Niue"],
"Palau" : ["Palaos"],
"Papua New Guinea" : ["Papúa Nueva Guinea", "Papua", "Papua Nueva Guinea"],
"Samoa" : ["Samoa"],
"Tonga" : ["Tonga"],
"Tuvalu" : ["Tuvalu"],
"Vanuatu" : ["Vanuatu"],
}

function convertir(pais){
  let traduccion = [];
  for(var i in paises) if(paises[i].some(p => p.toLowerCase()===pais.toLowerCase())) traduccion.push(i), traduccion.push(paises[i])
  return traduccion;
}

module.exports = {convertir};
